apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../k8s/base
- ingress.yaml

images:
- name: frontend-image
  newName: ghcr.io/koqsz/devops-demo-frontend
  newTag: latest
- name: backend-image
  newName: ghcr.io/koqsz/devops-demo-backend
  newTag: latest

patches:
- path: patches/frontend-deployment.yaml
- path: patches/frontend-service.yaml
- path: patches/backend-deployment.yaml
