apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../k8s/base
- ingress.yaml

images:
- name: backend-image
  newName: ghcr.io/koqsz/devops-demo-backend
  newTag: 074811d15bcbc25099e0a6b9a739f1ab3c819ca0
- name: frontend-image
  newName: ghcr.io/koqsz/devops-demo-frontend
  newTag: 074811d15bcbc25099e0a6b9a739f1ab3c819ca0

patches:
- path: patches/frontend-deployment.yaml
- path: patches/frontend-service.yaml
- path: patches/backend-deployment.yaml
