apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-demo

resources:
  - namespace.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/ingress.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/configmap.yaml
  - database/statefulset.yaml
  - database/service.yaml
  - database/secret.yaml
  - database/configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: devops-demo
    includeSelectors: true
