apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: backend-image
  newName: devops-demo-backend
  newTag: latest
- name: frontend-image
  newName: devops-demo-frontend
  newTag: latest

