apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

images:
  - name: frontend-image
    newName: ghcr.io/OWNER/devops-demo-frontend
    newTag: latest
  - name: backend-image
    newName: ghcr.io/OWNER/devops-demo-backend
    newTag: latest
